#!/usr/bin/env python

import os
import re
import socket
import sys
from os.path import abspath, dirname, join

from IP2Location import IP2Location

default = join(dirname(abspath(__file__)), 'IP2LOCATION-LITE-DB11.BIN')
DB_PATH = os.environ.get('IP2DB_PATH', default)

if os.path.isfile(DB_PATH):
    ip2loc = IP2Location(DB_PATH)
else:
    print("\033[91mNot found the IP2Location DB file.\033[0m\n"
          "You can download it from 'https://lite.ip2location.com/database-download'")
    sys.exit(1)


def print_err(host, msg):
    '''打印错误信息'''
    err_info = f'{host:15s} -> {msg}'
    print('\033[91m%s\033[0m' % err_info)


def is_ip(addr):
    '''检查是否时 IP 地址'''
    IP_PATTERN = (r'^(2(5[0-5]|[0-4]\d)|1\d\d|[1-9]\d|\d)'
                  r'(\.(2(5[0-5]|[0-4]\d)|1\d\d|[1-9]\d|\d)){3}$')
    return True if re.match(IP_PATTERN, addr) else False


def dns(host):
    '''获取 IP 地址'''
    try:
        for family, *_, addr in socket.getaddrinfo(host, None):
            if family == socket.AF_INET:
                return addr[0]
    except socket.error as e:
        print_err(host, e)


def chk_ip(ip: str):
    '''检查 IP'''
    result = ip2loc.get_all(ip)
    addr = f'[{result.country_short}] {result.region} / {result.city}'
    print(f'{ip:15s} -> {addr}')


if __name__ == '__main__':
    if len(sys.argv) > 1:
        for ip in sys.argv[1:]:
            try:
                if not is_ip(ip):
                    ip = dns(ip)
                    if ip is None:
                        continue
                chk_ip(ip)
            except KeyboardInterrupt:
                print('\nchkip: user abort.')
                sys.exit(1)
    else:
        print('usage: chkip IP1 [IP2 IP3 ...]')
        sys.exit(1)
