#!/bin/bash

RED="\033[1;31m"
ORANGE="\033[0;33m"
GRAY="\033[0;37m"
END="\033[0m"


if [[ $# == 0 ]]; then
    TARGET="."  # 无任何参数时，遍历选择当前目录
else
    TARGET=$*
fi

# 删除 .DS_Store 文件
find $TARGET -type f -name .DS_Store -delete


# 从指定的目录中查找空目录
num=0
while IFS= read -r d; do
    if [[ "$d" != "." && "$d" != "./" ]];then
        num=$[num + 1]
        printf "$ORANGE%2d  $d$END\n" $num
    fi
done < <(find $TARGET -type d -empty)

echo

if [[ $num > 0 ]]; then
    printf "${RED}Are you sure to delete these directories?$END (y/n) "
    read -n 1 DEL

    if [[ "$DEL" == "y" || "$DEL" == "Y" ]];then
        printf "\nDeleting...\n"
        find $TARGET -type d -empty -delete  # 同样的命令，加上 -delete 参数
    else
        printf "\nCancel\n"
    fi
else
    printf "Not found any empty directories.\n"
fi
