#!/bin/bash

ONLY_CHECK=flase
TARGET=''

RED="\033[0;31m"
LRED="\033[1;31m"

YELLOW="\033[1;33m"
ORANGE="\033[0;33m"

GRAY="\033[0;37m"
NON="\033[0m"


if [[ $# == 0 ]]; then
    echo "Usage: clean_empty_dir [-c] DIRECTORY"
    exit 1
elif [[ $# == 1 ]]; then
    TARGET=$1
else
    if [[ "$1" == '-c' ]]; then
        ONLY_CHECK=true
    fi
    TARGET=$2
fi


if [[ ! -d $TARGET ]]; then
    echo "$TARGET is not a valid directory."
    exit 1
fi


function is_empty() {
    if ls -A $1 | grep -v DS_Store > /dev/null; then
        return 1
    else
        return 0
    fi
}


for cur_dir in `find $TARGET -type d | sort -r`
do
    if is_empty $cur_dir; then
        if [[ $ONLY_CHECK = true ]];then
            printf "${ORANGE}EmptyDir: $cur_dir$NON\n"
        else
            printf "${RED}Deleting: $cur_dir$NON\n"
            rm -r $cur_dir
        fi
    fi
done
