#!/bin/bash

# set filename with crc32

for filename in $*
do
    if [[ -f $filename ]]; then
        hash_code=`crc32 $filename`
        ext_name=`echo "${filename##*.}" | tr '[:upper:]' '[:lower:]'`
        new_name="$hash_code.$ext_name"
        mv -nv $filename $new_name
    fi
done
