#!/bin/bash

# list files of each dir

if [[ $# == 0 ]]; then
    dirs=("./")
else
    dirs=$@
fi

for dir in $dirs
do
    if [ -d $dir ]; then
        cnt=`find $dir -name "[!.]*" -type file | wc -l`
        printf "%6s %s\n" $cnt $dir
    fi
done
