#!/bin/bash

OPEN=false
DELETE=false

while getopts ":dhor:" opt; do
  case $opt in
    d)
        DELETE=true
        ;;

    o)
        OPEN=true
        ;;
    r)
        RENAME=$OPTARG
        ;;
    *)
        echo "Usage: fd [-d -o -h] [-r RENAME] kw1[,kw2,kw3,...] [dir1 dir2 dir3 ...]" && exit 0
        ;;
  esac
done
shift $((OPTIND -1))

[[ -z "$@" ]] && echo "Usage: fd [-d -o -h] [-r RENAME] kw1[,kw2,kw3,...] [dir1 dir2 dir3 ...]" && exit 1

DIRS=$( [ -z "$2" ] && echo "." || echo "${@:2}" )
if [ -f $1 ]; then
    KWARGS=$( < $1 )
else
    KWARGS=$( echo $1 | tr "," "\n" )
fi

FILES=""
for kw in $KWARGS; do
    res=`find $DIRS -type f -name "$kw*"`
    if [ -n "$res" ]; then
        FILES="$FILES $res"
    else
        RED='\033[1;31m'
        YELLOW='\033[1;36m'
        NC='\033[0m'
        printf "${RED}Not found: ${YELLOW}$kw${NC}\n"
    fi
done

if [ -n "$FILES" ]; then
    ls -ilh $FILES
    if [[ $OPEN == true ]]; then
        open $FILES
    elif [[ $DELETE == true ]]; then
        read -p "Delete these files? [y/n] " -n 1 -r REPLY
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -v $FILES
        fi
    elif [[ -n "$RENAME" ]]; then
        read -p "Rename these files? [y/n] " -n 1 -r REPLY
        echo
        if [[  $REPLY =~ ^[Yy]$ ]]; then
            for f in $FILES; do
                parent=$(dirname $f)
                fullpath="$parent/$RENAME"
                mv -v $f $fullpath
            done
        fi
    fi
fi
