#!/bin/bash

# fix brew include files

CURRENT_DIR=$PWD
cd $BREWHOME/include
for dir in `find -L ../opt -name include`
do
    for include in `ls $dir`
    do
        local SRC="$dir/$include"
        if [ -d $SRC ] || [[ ${SRC##*.} == "h" ]]; then
            local DST="./$include"
            [[ -e $DST ]] || echo "ln -s $SRC $DST"
        fi
    done
done
cd $CURRENT_DIR
