#!/bin/bash
# 大小关系: maxfiles >= maxfilesperproc >= ulimit

# 全局最大连接数 (系统默认: 12288)
sudo -H sysctl -w kern.maxfiles=262143

# 单个进程最大连接数 (系统默认: 10240)
sudo -H sysctl -w kern.maxfilesperproc=65535

# 动态端口号范围 (系统默认: 49152 ~ 65535)
sudo -H sysctl -w net.inet.ip.portrange.first=10240
sudo -H sysctl -w net.inet.ip.portrange.last=65535
