#!/bin/bash

# open a ssh proxy

host=${1:-"bee"}
port=${2:-1086}
if ! lsof -sTCP:LISTEN -iTCP:$port > /dev/null
then
    ssh -qTfnN -D $port ubuntu@$host
    echo "Proxy:"
    echo "    remote host: $host"
    echo "    local  port: $port"
else
    echo "local port $port in used"
fi
